# pluto-export.toml

[Export]
# turn export on
enabled = true

# where to put the generated site (what GitHub Pages will serve)
output_dir = "docs"

# precompute all cells so the site is fully static
precompute = true

# optional: keep a cache of computed notebook state between builds (faster CI)
cache = true

# optional: clear old cache before exporting (good if you change deps often)
clear_old_cache = true

[SliderServer]
# we're doing a static export only
enabled = false
