# pluto-export.toml  (for PlutoSliderServer v1.5.0)

[Export]
enabled = true

# Where to write the static site:
output_dir = "docs"

# Cache behavior:
ignore_cache = false          # use cache if present (faster)
cache_dir = ".pluto_export_cache"

# Bake (precompute) all cell outputs into the HTML:
baked_state = true

# Optional niceties:
disable_ui = true             # hide Pluto's UI chrome in exported pages
exclude = []                  # e.g. ["notebooks/drafts/*"] if needed

[SliderServer]
enabled = false
