[Export]
enabled = true

# Where the static site will go
output_dir = "docs"

# Cache settings
ignore_cache = false
cache_dir = ".pluto_export_cache"

# Bake notebook state into the HTML
baked_state = true

# MUST be a list of notebook files to bake
baked_notebookfile = ["notebooks/index.jl"]

# Optional: hide Pluto’s sidebar UI in the export
disable_ui = true

# Optional: nothing excluded
exclude = []

[SliderServer]
enabled = false
