#!/bin/bash
set -e

JVER=1.10.5
JDIR="$HOME/julia-$JVER"

if [ ! -x "$JDIR/bin/julia" ]; then
  echo ">> Installing Julia $JVER to $JDIR"
  curl -L "https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-$JVER-linux-x86_64.tar.gz" | tar -xz -C "$HOME"
fi

export PATH="$JDIR/bin:$PATH"
echo ">> Instantiating & precompiling Julia project"
julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate(); Pkg.precompile()'
