#!/bin/bash
set -Eeuo pipefail
echo ">>> binder/start running..."

JVER="${JVER:-1.10.5}"
export PATH="$HOME/julia-$JVER/bin:$PATH"

exec julia --color=yes -e '
using Pluto
Pluto.run(
  host="0.0.0.0",
  port=parse(Int, get(ENV, "BINDER_PORT", "8888")),
  require_secret_for_open_links=false,
  require_secret_for_access=false,
  launch_browser=false
)'
