name: Prebuild Binder

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Binder image (no push, just warm cache)
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: 'true'
          # Optional: force a repo2docker version
          # FORCE_REPO2DOCKER_VERSION: 'repo2docker==2024.07.0'
